### ISSUE TITLE
align different bootstrap functions

### ISSUE THREAD

**Issue by kuriwaki** [mattblackwell/DirectEffects#5]
Currently the bootstrap in `boots_g` and the sensitivity analysis `cdesens` is not outlined the same way. Would probably make things easier if these were standardized and comparable.

**Comment by mattblackwell** [comment]
189e08d helps a bit on this by making the bootstrap arguments the same (and adds analytic variance for the sensitivity analysis)

**Comment by mattblackwell** [comment]
This is closed in version 0.2 f1ee624b01ecf97ed73a55a2f07de2ce07dae5e5 since the new architecture means `boots_g` simply calls `sequential_g` but `cdesens` implements the core algorithm itself.
